"""add required core tasks to days

Revision ID: 439ac7ef4645
Revises: baecd7f241d9
Create Date: 2026-09-13 00:16:43.499326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "439ac7ef4645"
down_revision: str | Sequence[str] | None = "baecd7f241d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "days", sa.Column("required_core_tasks", sa.Integer(), server_default="5", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("days", "required_core_tasks")
    # ### end Alembic commands ###
