"""add users and ownership

Revision ID: 906934f1ec46
Revises: 439ac7ef4645
Create Date: 2026-09-22 00:48:16.409506

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "906934f1ec46"
down_revision: str | Sequence[str] | None = "439ac7ef4645"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.add_column("days", sa.Column("user_id", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("days_date_key"), "days", type_="unique")
    op.add_column("tasks", sa.Column("user_id", sa.Integer(), nullable=True))

    connection = op.get_bind()

    legacy_user_id = connection.execute(
        sa.text(
            """
            INSERT INTO users (email, hashed_password)
            VALUES (:email, NULL)
            RETURNING id
            """
        ),
        {"email": "legacy@win-the-future.invalid"},
    ).scalar_one()

    connection.execute(
        sa.text(
            """
            UPDATE days
            SET user_id = :user_id
            WHERE user_id IS NULL
            """
        ),
        {"user_id": legacy_user_id},
    )

    connection.execute(
        sa.text(
            """
            UPDATE tasks
            SET user_id = :user_id
            WHERE user_id IS NULL
            """
        ),
        {"user_id": legacy_user_id},
    )

    op.alter_column(
        "days",
        "user_id",
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.alter_column(
        "tasks",
        "user_id",
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.create_index(op.f("ix_days_user_id"), "days", ["user_id"], unique=False)
    op.create_unique_constraint("uq_days_user_id_date", "days", ["user_id", "date"])
    op.create_foreign_key("fk_days_user_id_users", "days", "users", ["user_id"], ["id"])
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_foreign_key("fk_tasks_user_id_users", "tasks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    duplicate_dates = connection.execute(
        sa.text(
            """
            SELECT date
            FROM days
            GROUP BY date
            HAVING COUNT(*) > 1
            LIMIT 1
            """
        )
    ).first()

    if duplicate_dates is not None:
        raise RuntimeError("Cannot downgrade: multiple users have days with the same date.")

    op.drop_constraint("fk_tasks_user_id_users", "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_column("tasks", "user_id")
    op.drop_constraint("fk_days_user_id_users", "days", type_="foreignkey")
    op.drop_constraint("uq_days_user_id_date", "days", type_="unique")
    op.drop_index(op.f("ix_days_user_id"), table_name="days")
    op.create_unique_constraint(
        op.f("days_date_key"), "days", ["date"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("days", "user_id")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
