"""create days and tasks

Revision ID: baecd7f241d9
Revises:
Create Date: 2026-09-12 17:21:43.993319

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baecd7f241d9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("is_won", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "category", sa.Enum("MIND", "BODY", "MONEY", name="task_category"), nullable=False
        ),
        sa.Column("is_completed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_bonus", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "estimated_minutes IS NULL OR (estimated_minutes > 0 AND estimated_minutes <= 120)",
            name="check_task_estimated_minutes",
        ),
        sa.ForeignKeyConstraint(["day_id"], ["days.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_day_id"), "tasks", ["day_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_day_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
    sa.Enum(
        "MIND",
        "BODY",
        "MONEY",
        name="task_category",
    ).drop(op.get_bind(), checkfirst=True)

    op.drop_table("days")
